core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather_app/urls.py
from django.urls import path
from . import views



app_name = 'weather'

urlpatterns = [
    path('user/login/', views.login_view, name='login'),
    path('user/signin/', views.register_view, name='register'),
    path('user/create/', views.create_user, name="create"),
    path('user/logout/', views.logout_view, name='logout'),

    path('', views.home_view, name='home'),
    path('city/', views.get_info, name='get_city'),
    path('delete/city/<int:pk>', views.delete_view, name="delete")
]

weather_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    email = models.EmailField(max_length=200, null=False, blank=False, unique=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    
class location(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    location_name = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        return self.location_name

weather_app/forms.py
from django import forms
from django.forms import PasswordInput
from .models import CustomUser


class LoginForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password']
        widgets = {
            'password': PasswordInput(attrs={'type': 'password'}),
        }

class RegisterForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username','email','password']
        widgets = {
            'password': PasswordInput(attrs={'type': 'password'}),
        }

weather_app/views.py
from django.shortcuts import render, redirect
from dotenv import load_dotenv
import os
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required 
from .forms import LoginForm, RegisterForm
from django.http import HttpResponse, Http404
from django.contrib.auth import login, logout, authenticate
from .models import CustomUser, location
import requests

load_dotenv()

def login_view(request):
    if request.user.is_authenticated:
        return redirect("weather:home")
    if request.method == 'GET':
        form = LoginForm
        return render(request, 'login.html', {'form':form})
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("weather:home")
        else:
            return HttpResponse('crendeciais erradas')

@require_GET
def register_view(request):
    if request.user.is_authenticated:
        return redirect("weather:home")
    else:
        form = RegisterForm
        return render(request, 'register.html', {'form': form})
       
@require_POST
def create_user(request):
    if not request.POST:
        raise Http404()
    
    form = RegisterForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = CustomUser.objects.create(username=username, email=email)
        user.set_password(password)
        user.save()
        return redirect('weather:login') 
    return redirect('weather:register')       

def logout_view(request):
    logout(request)
    return redirect('weather:login')

@login_required
def home_view(request):    
    cities = location.objects.filter(user=request.user)
    token = os.environ.get('API_TOKEN')
    
    weather_data = []

    for city in cities:
        url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&lang=en&units=metric&appid={token}"
        r = requests.get(url.format(city)).json()
        
        
        city_weather = {    
            'id': city.id,
            'city': city,
            'temp': r['main']['temp'],
            'description': r['weather'][0]['description'],
            'weather_icon': r['weather'][0]['description'].replace(" ", ""), 
        }

        weather_data.append(city_weather)

    context = {'weather_data':weather_data}
    return render(request, 'home.html', context)

def get_info(request):
    city_name = request.POST['city']
    city = location(location_name=city_name, user=request.user)
    city.save()
    return redirect('weather:home') 

def delete_view(request, pk):
    obj = location.objects.get(pk=pk)
    obj.delete()
    return redirect('weather:home') 

weather_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Weather APP</title>
</head>

<body>
    <header class="header">
        <h1>How's the weather?</h1>
    </header>
    <div class="main-container">
        <div class="main-content">
            <form action="{% url 'weather:get_city' %}" method="POST" class="form">
                {%csrf_token%}
                <input type="text" name="city" placeholder="City Name">
                <button type="submit">Add City</button>
            </form>
            <div class="flex-items">
                {% for city in weather_data %} 
                    <div class="weather-container">
                        <div class="img {{ city.weather_icon }}"></div>
                        <div class="weather-details flex-column">
                            <p class="city-name">{{ city.city }}</p>
                            <p class="temperature">{{ city.temp }}° C</p>
                            <P class="weather-conditions">{{ city.description }}</P>
                        </div>
                        <a href="{% url 'weather:delete' city.id %}" class="icon"><ion-icon name="trash"></ion-icon></a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <footer class="footer"></footer>
</body>

</html>

weather_app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form }}  
        <input type="submit" value="login">
    </form>
    <p><a href="{% url 'weather:register'%}">Register</a></p>
</body>
</html>

weather_app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="main-content center container">
        <h2>Register</h2>
    </div>
    <div class="main-content  short-container">
        <form action="{% url 'weather:create' %}" method="POST">
            {% csrf_token %}
            <div class="form-content form-content-grid">
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}

                    {% if field.help_text %}
                        <p class="help-text">
                            {{ field.help_text|safe }}
                        </p>
                    {% endif %}

                    {{ field.errors }}
                </div>
                {% endfor %}
            </div>

            <div class="form-content form-content-grid">
                <div class="form-group">
                    <button type="submit">Register</button>
                </div>
            </div>
        </form>
        <p><a href="{% url 'weather:login'%}">Login</a></p>
    </div>
</body>
</html>